DOCUMENT_TEMPLATES = [
    {
        "id": "car_insurance",
        "name": "Bilförsäkring",
        "description": "Försäkringsbrev, villkor och ersättningsregler för bil.",
        "fields": ["försäkringsbolag", "försäkringsnummer", "registreringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under försäkringstid och minst tre år efter avslut.",
        "keywords": ["bil", "försäkring", "krock", "självrisk", "vagnskada"],
    },
    {
        "id": "home_insurance",
        "name": "Hemförsäkring",
        "description": "Hemförsäkring, ansvar, reseskydd och lösöre.",
        "fields": ["försäkringsbolag", "försäkringsnummer", "adress", "lösöresbelopp", "giltig_till"],
        "retention": "Spara aktuell version och tidigare villkor vid pågående ärenden.",
        "keywords": ["hem", "försäkring", "resa", "lösöre", "ansvar"],
    },
    {
        "id": "personal_insurance",
        "name": "Personförsäkring",
        "description": "Liv-, olycksfalls-, barn- och sjukförsäkringar.",
        "fields": ["försäkrad", "försäkringsnummer", "förmånstagare", "belopp", "giltig_till"],
        "retention": "Spara så länge försäkringen gäller och under eventuella skadeärenden.",
        "keywords": ["person", "olycksfall", "sjuk", "livförsäkring"],
    },
    {
        "id": "health_insurance",
        "name": "Sjukförsäkring",
        "description": "Privat sjukförsäkring, ersättningsvillkor, vårdgarantier och intyg.",
        "fields": ["försäkrad", "försäkringsbolag", "försäkringsnummer", "ersättning", "giltig_till"],
        "retention": "Spara så länge försäkringen gäller och under pågående vård- eller ersättningsärenden.",
        "keywords": ["sjukförsäkring", "sjukdom", "vård", "ersättning", "försäkring"],
    },
    {
        "id": "dog_insurance",
        "name": "Hundförsäkring",
        "description": "Veterinärvård, livförsäkring, rehabilitering och rasrelaterade villkor för hund.",
        "fields": ["hund", "ras", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under försäkringstiden och under pågående veterinär- eller skadeärenden.",
        "keywords": ["hund", "djur", "veterinär", "försäkring", "självrisk"],
    },
    {
        "id": "cat_insurance",
        "name": "Kattförsäkring",
        "description": "Veterinärvård, livförsäkring och läkemedelsvillkor för katt.",
        "fields": ["katt", "ras", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under försäkringstiden och under pågående veterinär- eller skadeärenden.",
        "keywords": ["katt", "djur", "veterinär", "försäkring", "självrisk"],
    },
    {
        "id": "pet_insurance",
        "name": "Djurförsäkring",
        "description": "Generell försäkring för sällskapsdjur, veterinärvård och ansvar.",
        "fields": ["djur", "art", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara så länge försäkringen gäller och under relevanta skade- eller vårdärenden.",
        "keywords": ["djur", "sällskapsdjur", "veterinär", "försäkring"],
    },
    {
        "id": "travel_insurance",
        "name": "Reseförsäkring",
        "description": "Reseskydd, avbeställningsskydd, vård utomlands och bagage.",
        "fields": ["resenär", "resa", "försäkringsbolag", "försäkringsnummer", "giltig_period"],
        "retention": "Spara tills resan och eventuella ersättningsärenden är avslutade.",
        "keywords": ["resa", "avbeställning", "bagage", "utomlands", "försäkring"],
    },
    {
        "id": "accident_insurance",
        "name": "Olycksfallsförsäkring",
        "description": "Olycksfall, invaliditetsersättning, rehabilitering och vårdkostnader.",
        "fields": ["försäkrad", "försäkringsbolag", "försäkringsnummer", "belopp", "giltig_till"],
        "retention": "Spara långsiktigt vid personskada och under alla skadeärenden.",
        "keywords": ["olycksfall", "personskada", "invaliditet", "ersättning"],
    },
    {
        "id": "life_insurance",
        "name": "Livförsäkring",
        "description": "Livförsäkring, förmånstagare, försäkringsbelopp och villkor.",
        "fields": ["försäkrad", "förmånstagare", "försäkringsbolag", "försäkringsnummer", "belopp"],
        "retention": "Spara långsiktigt och uppdatera vid ändrade familje- eller ekonomiförhållanden.",
        "keywords": ["livförsäkring", "förmånstagare", "belopp", "dödsfall"],
    },
    {
        "id": "child_insurance",
        "name": "Barnförsäkring",
        "description": "Barnförsäkring, sjukdom, olycksfall, diagnosersättning och invaliditet.",
        "fields": ["barn", "vårdnadshavare", "försäkringsbolag", "försäkringsnummer", "giltig_till"],
        "retention": "Spara långsiktigt och under alla vård- eller ersättningsärenden.",
        "keywords": ["barn", "sjukdom", "olycksfall", "diagnos", "försäkring"],
    },
    {
        "id": "pregnancy_insurance",
        "name": "Gravidförsäkring",
        "description": "Gravidförsäkring, komplikationer, förlossning och nyföddhetsvillkor.",
        "fields": ["försäkrad", "beräknat_datum", "försäkringsbolag", "försäkringsnummer", "giltig_period"],
        "retention": "Spara under graviditet, förlossning och eventuella efterföljande ärenden.",
        "keywords": ["gravid", "förlossning", "barn", "komplikation", "försäkring"],
    },
    {
        "id": "income_insurance",
        "name": "Inkomstförsäkring",
        "description": "Inkomstskydd vid arbetslöshet, kvalifikationstid och ersättningsnivåer.",
        "fields": ["försäkrad", "fackförbund", "försäkringsbolag", "ersättningsnivå", "giltig_till"],
        "retention": "Spara under medlemskap och tills arbetslöshets- eller ersättningsärenden är avslutade.",
        "keywords": ["inkomst", "arbetslöshet", "a-kassa", "fack", "ersättning"],
    },
    {
        "id": "unemployment_insurance",
        "name": "Arbetslöshetsförsäkring",
        "description": "A-kassa, medlemskap, ersättningsbeslut och villkor vid arbetslöshet.",
        "fields": ["a_kassa", "medlemsnummer", "period", "ersättning", "status"],
        "retention": "Spara under medlemskap och vid pågående eller överklagade ersättningsärenden.",
        "keywords": ["arbetslöshet", "a-kassa", "medlemskap", "ersättning"],
    },
    {
        "id": "liability_insurance",
        "name": "Ansvarsförsäkring",
        "description": "Privat eller separat ansvarsskydd, skadeståndsanspråk och rättsliga villkor.",
        "fields": ["försäkrad", "försäkringsbolag", "försäkringsnummer", "ansvarsbelopp", "giltig_till"],
        "retention": "Spara under försäkringstiden och tills eventuella krav eller tvister är avslutade.",
        "keywords": ["ansvar", "skadestånd", "krav", "försäkring"],
    },
    {
        "id": "legal_expenses_insurance",
        "name": "Rättsskyddsförsäkring",
        "description": "Rättsskydd, juridiska kostnader, ombud och tvistvillkor.",
        "fields": ["försäkrad", "försäkringsbolag", "försäkringsnummer", "ärende", "beloppsgräns"],
        "retention": "Spara under försäkringstiden och tills juridiska ärenden är helt avslutade.",
        "keywords": ["rättsskydd", "juridik", "tvist", "ombud", "försäkring"],
    },
    {
        "id": "boat_insurance",
        "name": "Båtförsäkring",
        "description": "Båt, motor, utrustning, ansvar, uppläggning och sjöskador.",
        "fields": ["båt", "motor", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under ägande och vid pågående skade- eller försäljningsärenden.",
        "keywords": ["båt", "motor", "sjöskada", "ansvar", "försäkring"],
    },
    {
        "id": "motorcycle_insurance",
        "name": "Motorcykelförsäkring",
        "description": "Trafik, halvförsäkring, helförsäkring, stöld och vagnskada för motorcykel.",
        "fields": ["registreringsnummer", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under ägandet och tills skadeärenden är avslutade.",
        "keywords": ["motorcykel", "mc", "trafik", "stöld", "vagnskada"],
    },
    {
        "id": "moped_insurance",
        "name": "Mopedförsäkring",
        "description": "Trafikförsäkring, stöld, skador och villkor för moped.",
        "fields": ["registreringsnummer", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under ägandet och tills skadeärenden är avslutade.",
        "keywords": ["moped", "trafik", "stöld", "skada", "försäkring"],
    },
    {
        "id": "caravan_insurance",
        "name": "Husvagnsförsäkring",
        "description": "Husvagn, förtält, lösöre, trafikrelaterade skador och uppställning.",
        "fields": ["registreringsnummer", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under ägandet och tills skadeärenden är avslutade.",
        "keywords": ["husvagn", "förtält", "lösöre", "uppställning", "försäkring"],
    },
    {
        "id": "motorhome_insurance",
        "name": "Husbilsförsäkring",
        "description": "Husbil, trafik, vagnskada, lösöre och reseanknutna villkor.",
        "fields": ["registreringsnummer", "försäkringsbolag", "försäkringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under ägandet och tills skadeärenden är avslutade.",
        "keywords": ["husbil", "trafik", "vagnskada", "lösöre", "försäkring"],
    },
    {
        "id": "cottage_insurance",
        "name": "Fritidshusförsäkring",
        "description": "Fritidshus, byggnad, tomt, lösöre, ansvar och naturskador.",
        "fields": ["fastighet", "adress", "försäkringsbolag", "försäkringsnummer", "giltig_till"],
        "retention": "Spara under ägandet och under eventuella skade- eller byggärenden.",
        "keywords": ["fritidshus", "stuga", "byggnad", "lösöre", "försäkring"],
    },
    {
        "id": "condominium_insurance",
        "name": "Bostadsrättsförsäkring",
        "description": "Bostadsrättstillägg, fast inredning, ansvar och vattenskador.",
        "fields": ["adress", "förening", "försäkringsbolag", "försäkringsnummer", "giltig_till"],
        "retention": "Spara under boendetiden och tills skade- eller tvistärenden är avslutade.",
        "keywords": ["bostadsrätt", "tillägg", "vattenskada", "inredning", "försäkring"],
    },
    {
        "id": "valuable_items_insurance",
        "name": "Värdesaksförsäkring",
        "description": "Särskild försäkring för smycken, klockor, konst, elektronik eller andra värdesaker.",
        "fields": ["föremål", "värde", "försäkringsbolag", "försäkringsnummer", "giltig_till"],
        "retention": "Spara tillsammans med kvitton, värderingar och bilder så länge föremålet ägs.",
        "keywords": ["värdesak", "smycke", "klocka", "konst", "försäkring"],
    },
    {
        "id": "claim_report",
        "name": "Skadeanmälan/olycksrapport",
        "description": "Skadeanmälningar, polisrapporter och korrespondens.",
        "fields": ["ärendenummer", "datum", "plats", "motpart", "status"],
        "retention": "Spara tills ärendet är helt avslutat och preskriptionstid passerat.",
        "keywords": ["skada", "olycka", "ärende", "rapport", "ersättning"],
    },
    {
        "id": "vehicle",
        "name": "Fordonsdokument",
        "description": "Registreringsbevis, service, besiktning och köpavtal.",
        "fields": ["registreringsnummer", "vin", "miltal", "datum", "verkstad"],
        "retention": "Spara under ägandet och vid försäljning som historik.",
        "keywords": ["fordon", "service", "besiktning", "registreringsbevis"],
    },
    {
        "id": "receipt",
        "name": "Kvitto",
        "description": "Kvitton för inköp, underlag och reklamation.",
        "fields": ["butik", "datum", "belopp", "moms", "betalmedel"],
        "retention": "Spara minst garantitiden eller enligt skattebehov.",
        "keywords": ["kvitto", "belopp", "moms", "inköp"],
    },
    {
        "id": "warranty_service",
        "name": "Garanti/service",
        "description": "Garantibevis, serviceavtal och reparationer.",
        "fields": ["produkt", "serienummer", "garanti_till", "leverantör", "ärendenummer"],
        "retention": "Spara under garanti- och reklamationstid.",
        "keywords": ["garanti", "service", "reparation", "serienummer"],
    },
    {
        "id": "tax_return",
        "name": "Skattedeklaration",
        "description": "Deklarationer och beslut från Skatteverket.",
        "fields": ["år", "beslutsdatum", "skatt", "rot_rut", "bilagor"],
        "retention": "Spara minst sju år om dokumentet styrker avdrag eller inkomster.",
        "keywords": ["deklaration", "skatt", "beslut", "avdrag"],
    },
    {
        "id": "tax_evidence",
        "name": "Skatteunderlag",
        "description": "Kontrolluppgifter, avdrag, resor och försäljningsunderlag.",
        "fields": ["år", "typ", "belopp", "motpart", "underlag"],
        "retention": "Spara minst sju år.",
        "keywords": ["underlag", "kontrolluppgift", "avdrag", "skatt"],
    },
    {
        "id": "bank_statement",
        "name": "Bankutdrag",
        "description": "Kontoutdrag, transaktionslistor och bankintyg.",
        "fields": ["bank", "konto", "period", "saldo", "valuta"],
        "retention": "Spara efter behov för skatt, tvister och större köp.",
        "keywords": ["bank", "konto", "utdrag", "transaktion"],
    },
    {
        "id": "loan_credit",
        "name": "Lån/kredit",
        "description": "Låneavtal, amorteringsplaner och kreditvillkor.",
        "fields": ["långivare", "avtalsnummer", "ränta", "löptid", "skuld"],
        "retention": "Spara tills lånet är avslutat och slutbesked finns.",
        "keywords": ["lån", "kredit", "ränta", "amortering"],
    },
    {
        "id": "bank_account",
        "name": "Bankkonto",
        "description": "Kontoinformation, öppningshandlingar, villkor och kontobevis.",
        "fields": ["bank", "kontonummer", "iban", "kontotyp", "villkor", "giltig_till"],
        "retention": "Spara så länge kontot används och vid pågående skatte- eller tvistärenden.",
        "keywords": ["bank", "konto", "iban", "kontobevis", "villkor"],
    },
    {
        "id": "credit_card",
        "name": "Kreditkort",
        "description": "Kreditkortsavtal, kontoutdrag, kreditgräns, avgifter och reklamationer.",
        "fields": ["kortutgivare", "kortnummer_maskat", "kreditgräns", "ränta", "giltig_till"],
        "retention": "Spara under kortets giltighetstid och tills reklamationer eller krav är avslutade.",
        "keywords": ["kreditkort", "kort", "kredit", "avgift", "reklamation"],
    },
    {
        "id": "debit_card",
        "name": "Bankkort",
        "description": "Bankkort, kortvillkor, spärrinformation och kortreklamationer.",
        "fields": ["bank", "kortnummer_maskat", "korttyp", "giltig_till", "status"],
        "retention": "Spara under kortets giltighetstid och vid pågående reklamationer.",
        "keywords": ["bankkort", "kort", "spärr", "reklamation", "betalning"],
    },
    {
        "id": "mortgage",
        "name": "Bolån",
        "description": "Bolåneavtal, amortering, ränta, bindningstid och säkerheter.",
        "fields": ["bank", "lånenummer", "fastighet", "ränta", "bindningstid", "skuld"],
        "retention": "Spara tills lånet är avslutat och slutbesked, pantbrev eller historik inte längre behövs.",
        "keywords": ["bolån", "hypotek", "amortering", "ränta", "pantbrev"],
    },
    {
        "id": "consumer_credit",
        "name": "Konsumtionskredit",
        "description": "Privatlån, delbetalning, blancolån och andra konsumentkrediter.",
        "fields": ["långivare", "avtalsnummer", "belopp", "ränta", "löptid", "skuld"],
        "retention": "Spara tills krediten är avslutad och slutbesked finns.",
        "keywords": ["konsumtionskredit", "privatlån", "delbetalning", "blanco", "ränta"],
    },
    {
        "id": "securities_account",
        "name": "Värdepapperskonto",
        "description": "VP-konto, depå, innehavsbesked, transaktioner och villkor.",
        "fields": ["institut", "kontonummer", "depåtyp", "innehav", "period", "valuta"],
        "retention": "Spara långsiktigt för skatt, anskaffningsvärden och kapitalhistorik.",
        "keywords": ["värdepapper", "depå", "aktier", "innehav", "transaktion"],
    },
    {
        "id": "investment_savings_account",
        "name": "ISK",
        "description": "Investeringssparkonto, årsbesked, schablonunderlag och innehav.",
        "fields": ["institut", "kontonummer", "år", "schablonunderlag", "innehav"],
        "retention": "Spara långsiktigt för deklaration och kapitalhistorik.",
        "keywords": ["isk", "investeringssparkonto", "schablon", "värdepapper", "deklaration"],
    },
    {
        "id": "fund_account",
        "name": "Fondkonto",
        "description": "Fondkonto, fondinnehav, köp, sälj, avgifter och årsbesked.",
        "fields": ["institut", "kontonummer", "fond", "andelar", "avgift", "period"],
        "retention": "Spara långsiktigt för skatt, avgifter och anskaffningshistorik.",
        "keywords": ["fond", "fondkonto", "andelar", "avgift", "årsbesked"],
    },
    {
        "id": "pension_savings",
        "name": "Pensionssparande",
        "description": "Privat pensionssparande, tjänstepension, fondval och pensionsbesked.",
        "fields": ["institut", "försäkringsnummer", "sparform", "värde", "fondval", "period"],
        "retention": "Spara långsiktigt eftersom dokumenten påverkar pension och framtida utbetalningar.",
        "keywords": ["pension", "pensionssparande", "tjänstepension", "fondval", "utbetalning"],
    },
    {
        "id": "payment_service",
        "name": "Betaltjänst",
        "description": "Autogiro, e-faktura, Swish, betalningsuppdrag och betalningsvillkor.",
        "fields": ["leverantör", "konto", "mottagare", "betalningstyp", "referens", "status"],
        "retention": "Spara så länge tjänsten används och vid reklamationer eller betalningstvister.",
        "keywords": ["betaltjänst", "autogiro", "e-faktura", "swish", "betalning"],
    },
    {
        "id": "housing_rent_fee",
        "name": "Hyra/bostad/avgift",
        "description": "Hyresavtal, avgiftsavier och bostadskorrespondens.",
        "fields": ["adress", "hyresvärd", "period", "belopp", "avtalsnummer"],
        "retention": "Spara under boendetiden och vid pågående tvist.",
        "keywords": ["hyra", "bostad", "avgift", "avi"],
    },
    {
        "id": "home_purchase",
        "name": "Bostadsköp/lagfart/avtal",
        "description": "Köpebrev, pantbrev, lagfart, mäklarhandlingar.",
        "fields": ["fastighet", "adress", "köpeskilling", "datum", "mäklare"],
        "retention": "Spara permanent eller så länge bostaden ägs.",
        "keywords": ["bostadsköp", "lagfart", "pantbrev", "köpebrev"],
    },
    {
        "id": "utilities",
        "name": "El, vatten och bredband",
        "description": "Avtal, fakturor och mätvärden för hushållstjänster.",
        "fields": ["leverantör", "anläggningsid", "period", "belopp", "förbrukning"],
        "retention": "Spara enligt reklamations- och jämförelsebehov.",
        "keywords": ["el", "vatten", "bredband", "faktura", "förbrukning"],
    },
    {
        "id": "medical_record",
        "name": "Medicinsk journal",
        "description": "Journalutdrag, provsvar och vårdkorrespondens.",
        "fields": ["vårdgivare", "datum", "diagnos", "läkare", "ärende"],
        "retention": "Spara långsiktigt och med extra försiktighet.",
        "keywords": ["journal", "provsvar", "diagnos", "vård"],
    },
    {
        "id": "prescription",
        "name": "Recept/läkemedel",
        "description": "Recept, läkemedelslistor och instruktioner.",
        "fields": ["läkemedel", "dos", "läkare", "giltig_till", "apotek"],
        "retention": "Spara medan behandlingen pågår och vid relevant historik.",
        "keywords": ["recept", "läkemedel", "dos", "apotek"],
    },
    {
        "id": "employment",
        "name": "Arbetsavtal",
        "description": "Anställningsavtal, villkor och intyg.",
        "fields": ["arbetsgivare", "roll", "startdatum", "lön", "uppsägningstid"],
        "retention": "Spara långsiktigt för pension, inkomst och tvister.",
        "keywords": ["anställning", "arbetsavtal", "lön", "villkor"],
    },
    {
        "id": "salary_pension",
        "name": "Lön/pension",
        "description": "Lönespecifikationer, pensionsbesked och intyg.",
        "fields": ["arbetsgivare", "period", "bruttolön", "skatt", "pensionsinstitut"],
        "retention": "Spara långsiktigt eller enligt skatte- och pensionsbehov.",
        "keywords": ["lön", "pension", "specifikation", "inkomst"],
    },
    {
        "id": "legal_contract",
        "name": "Juridiskt avtal/fullmakt",
        "description": "Avtal, fullmakter, testamenten och juridiska beslut.",
        "fields": ["part", "datum", "giltig_till", "jurist", "ärende"],
        "retention": "Spara permanent om dokumentet har lång rättsverkan.",
        "keywords": ["avtal", "fullmakt", "juridik", "testamente"],
    },
    {
        "id": "identity",
        "name": "Identitet/pass/körkort",
        "description": "Identitetshandlingar, kopior och giltighetsdatum.",
        "fields": ["typ", "nummer", "utfärdare", "giltig_till", "land"],
        "retention": "Spara säkert; radera gamla kopior när de inte behövs.",
        "keywords": ["pass", "körkort", "id", "identitet"],
    },
    {
        "id": "password_vault_export",
        "name": "Lösenord/valvexport",
        "description": "Exporter, nödkuvert eller säkerhetskopior från lösenordshanterare.",
        "fields": ["källa", "exportdatum", "format", "omfattning", "ansvarig"],
        "retention": "Spara endast krypterat, håll aktuell version och radera gamla exporter när de ersatts.",
        "keywords": ["lösenord", "valv", "password manager", "export", "hemlighet"],
    },
    {
        "id": "recovery_codes",
        "name": "Återställningskoder",
        "description": "Backupkoder för tvåfaktor, kontoåterställning och nödåtkomst.",
        "fields": ["tjänst", "konto", "skapad", "förbrukade_koder", "förvaringsplats"],
        "retention": "Spara säkert tills koderna ersatts eller tjänsten avslutats.",
        "keywords": ["återställning", "backupkod", "2fa", "mfa", "konto"],
    },
    {
        "id": "api_keys_tokens",
        "name": "API-nycklar/tokens",
        "description": "API-nycklar, access tokens, webhook-hemligheter och integrationsuppgifter.",
        "fields": ["system", "nyckeltyp", "skapad", "behörighet", "rotation_senast"],
        "retention": "Spara endast aktuell eller revisionsrelevant version och rotera vid misstänkt exponering.",
        "keywords": ["api", "token", "nyckel", "webhook", "integration"],
    },
    {
        "id": "ssh_keys",
        "name": "SSH-nycklar",
        "description": "SSH-nycklar, public keys, nyckelkommentarer och åtkomstunderlag.",
        "fields": ["nyckelnamn", "fingerprint", "system", "skapad", "giltig_till"],
        "retention": "Spara säkert och gallra nycklar som inte längre har åtkomst.",
        "keywords": ["ssh", "nyckel", "fingerprint", "server", "åtkomst"],
    },
    {
        "id": "encryption_keys",
        "name": "Krypteringsnycklar",
        "description": "Krypteringsnycklar, nyckelmaterial, recovery keys och dekrypteringsinstruktioner.",
        "fields": ["system", "nyckeltyp", "fingerprint", "skapad", "förvaringsplats"],
        "retention": "Spara endast när det är nödvändigt och håll separat kontroll på åtkomst och rotation.",
        "keywords": ["kryptering", "nyckel", "recovery", "dekryptering", "hemlighet"],
    },
    {
        "id": "ssl_certificates",
        "name": "TLS/SSL-certifikat",
        "description": "Certifikat, privata nycklar, CSR, CA-kedjor och förnyelseunderlag.",
        "fields": ["domän", "utfärdare", "fingerprint", "giltig_till", "förnyelse"],
        "retention": "Spara aktuella certifikat och revisionsspår; radera privata nycklar som inte längre behövs.",
        "keywords": ["tls", "ssl", "certifikat", "domän", "förnyelse"],
    },
    {
        "id": "domain_dns",
        "name": "Domän/DNS",
        "description": "Domänregistrering, DNS-zoner, registraruppgifter och förnyelseinformation.",
        "fields": ["domän", "registrar", "namnservrar", "förnyas", "kontakt"],
        "retention": "Spara så länge domänen används och vid historiska flyttar eller tvister.",
        "keywords": ["domän", "dns", "registrar", "namnserver", "zon"],
    },
    {
        "id": "hosting_server",
        "name": "Hosting/server",
        "description": "Serveravtal, VPS, driftinformation, IP-adresser och åtkomstunderlag.",
        "fields": ["leverantör", "servernamn", "ip_adress", "avtal", "giltig_till"],
        "retention": "Spara under driftperioden och tills migreringar, fakturor eller incidenter är avslutade.",
        "keywords": ["hosting", "server", "vps", "ip", "drift"],
    },
    {
        "id": "network_config",
        "name": "Nätverkskonfiguration",
        "description": "Router-, brandväggs-, VPN-, VLAN- och Wi-Fi-konfigurationer.",
        "fields": ["plats", "enhet", "version", "exportdatum", "ansvarig"],
        "retention": "Spara aktuell konfiguration och historik som behövs för felsökning eller återställning.",
        "keywords": ["nätverk", "router", "brandvägg", "vpn", "wifi"],
    },
    {
        "id": "backup_recovery_plan",
        "name": "Backup/återställning",
        "description": "Backupplaner, återställningsrutiner, testprotokoll och lagringsplatser.",
        "fields": ["system", "backupplats", "frekvens", "senast_testad", "ansvarig"],
        "retention": "Spara aktuell plan och historik över återställningstester.",
        "keywords": ["backup", "återställning", "restore", "katastrof", "test"],
    },
    {
        "id": "software_license",
        "name": "Programlicens",
        "description": "Licensnycklar, abonnemang, EULA, aktiveringar och inköpsunderlag.",
        "fields": ["produkt", "licensnyckel", "leverantör", "antal", "giltig_till"],
        "retention": "Spara under licensperioden och för revisions- eller inköpshistorik.",
        "keywords": ["licens", "programvara", "abonnemang", "aktivering", "eula"],
    },
    {
        "id": "device_inventory_technical",
        "name": "Teknisk inventarie",
        "description": "Datorer, telefoner, nätverksenheter, serienummer, garanti och konfiguration.",
        "fields": ["enhet", "serienummer", "modell", "ägare", "plats", "garanti_till"],
        "retention": "Spara under ägandet och vid garanti-, försäkrings- eller serviceärenden.",
        "keywords": ["inventarie", "dator", "telefon", "serienummer", "garanti"],
    },
    {
        "id": "cloud_account",
        "name": "Molnkonto",
        "description": "Molnkonton, tenant-information, ägare, abonnemang och åtkomstmodell.",
        "fields": ["leverantör", "tenant", "konto", "ägare", "abonnemang", "status"],
        "retention": "Spara under kontots livstid och tills migrering eller avslut är verifierat.",
        "keywords": ["moln", "konto", "tenant", "aws", "azure", "google"],
    },
    {
        "id": "digital_subscription",
        "name": "Digital prenumeration",
        "description": "Digitala abonnemang, kontovillkor, förnyelser och uppsägningsinformation.",
        "fields": ["tjänst", "konto", "period", "kostnad", "förnyas", "uppsägning"],
        "retention": "Spara medan tjänsten används och tills uppsägning eller tvist är avslutad.",
        "keywords": ["prenumeration", "abonnemang", "digital", "konto", "förnyelse"],
    },
    {
        "id": "crypto_wallet",
        "name": "Kryptoplånbok",
        "description": "Wallet-underlag, seed-relaterad dokumentation, adresser och förvaringsrutiner.",
        "fields": ["wallet", "nätverk", "adress", "förvaringsplats", "skapad"],
        "retention": "Spara extremt säkert och endast med tydlig åtkomst- och arvsrutin.",
        "keywords": ["krypto", "wallet", "seed", "adress", "nyckel"],
    },
    {
        "id": "incident_security",
        "name": "Säkerhetsincident",
        "description": "Incidentrapporter, komprometterade konton, åtgärder och kommunikation.",
        "fields": ["datum", "system", "incidenttyp", "åtgärd", "status"],
        "retention": "Spara långsiktigt om incidenten påverkar säkerhet, ekonomi eller juridik.",
        "keywords": ["incident", "säkerhet", "intrång", "konto", "åtgärd"],
    },
    {
        "id": "general_document",
        "name": "Allmänt dokument",
        "description": "Övriga dokument som behöver arkiveras men inte passar en specifik mall.",
        "fields": ["titel", "datum", "avsändare", "ämne", "notering"],
        "retention": "Spara efter egen bedömning och gallra när dokumentet inte längre behövs.",
        "keywords": ["allmänt", "övrigt", "dokument", "arkiv"],
    },
    {
        "id": "invoice",
        "name": "Faktura",
        "description": "Fakturor, betalningsunderlag och krav.",
        "fields": ["leverantör", "fakturanummer", "förfallodatum", "belopp", "status"],
        "retention": "Spara minst enligt reklamations- och skattebehov.",
        "keywords": ["faktura", "betalning", "leverantör", "belopp"],
    },
    {
        "id": "generic_contract",
        "name": "Avtal",
        "description": "Generiska avtal, villkor och överenskommelser.",
        "fields": ["part", "motpart", "datum", "giltig_till", "uppsägning"],
        "retention": "Spara under avtalstiden och tills eventuella krav eller tvister är preskriberade.",
        "keywords": ["avtal", "villkor", "överenskommelse", "kontrakt"],
    },
    {
        "id": "certificate",
        "name": "Intyg/certifikat",
        "description": "Intyg, certifikat, bevis och formella utlåtanden.",
        "fields": ["utfärdare", "datum", "giltig_till", "mottagare", "ärende"],
        "retention": "Spara så länge intyget kan behövas för styrkande eller kontroll.",
        "keywords": ["intyg", "certifikat", "bevis", "utlåtande"],
    },
    {
        "id": "correspondence",
        "name": "Korrespondens",
        "description": "Brev, e-post, meddelanden och ärendekommunikation.",
        "fields": ["avsändare", "mottagare", "datum", "ärende", "kanal"],
        "retention": "Spara så länge kommunikationen behövs för ärendet eller historiken.",
        "keywords": ["brev", "e-post", "meddelande", "korrespondens"],
    },
    {
        "id": "manual_guide",
        "name": "Manual/guide",
        "description": "Manualer, instruktioner, guider och produktdokumentation.",
        "fields": ["produkt", "version", "leverantör", "datum", "ämne"],
        "retention": "Spara medan produkten eller tjänsten används.",
        "keywords": ["manual", "guide", "instruktion", "dokumentation"],
    },
    {
        "id": "application_form",
        "name": "Ansökan/blankett",
        "description": "Ifyllda blanketter, ansökningar och kompletteringar.",
        "fields": ["myndighet", "ärende", "datum", "status", "referens"],
        "retention": "Spara tills ärendet är avslutat och beslutet inte längre kan behöva styrkas.",
        "keywords": ["ansökan", "blankett", "ärende", "komplettering"],
    },
    {
        "id": "decision_notice",
        "name": "Beslut/besked",
        "description": "Beslut, besked, godkännanden och avslag från organisationer eller myndigheter.",
        "fields": ["avsändare", "beslutsdatum", "ärendenummer", "utfall", "överklagan_senast"],
        "retention": "Spara långsiktigt när beslutet påverkar rättigheter, ekonomi eller historik.",
        "keywords": ["beslut", "besked", "godkännande", "avslag"],
    },
    {
        "id": "inventory_list",
        "name": "Inventarielista",
        "description": "Listor över ägodelar, utrustning, serienummer och värden.",
        "fields": ["kategori", "produkt", "serienummer", "värde", "plats"],
        "retention": "Spara aktuell version och historik vid försäkrings- eller garantiärenden.",
        "keywords": ["inventarie", "lista", "ägodelar", "utrustning"],
    },
    {
        "id": "photo_evidence",
        "name": "Bildbevis",
        "description": "Bilder som styrker skick, skada, innehav eller händelse.",
        "fields": ["datum", "plats", "motiv", "ärende", "kopplat_dokument"],
        "retention": "Spara tillsammans med relevant ärende, försäkring eller avtal.",
        "keywords": ["bild", "foto", "bevis", "skada", "händelse"],
    },
]

TEMPLATE_BY_ID = {item["id"]: item for item in DOCUMENT_TEMPLATES}
