DOCUMENT_TEMPLATES = [
    {
        "id": "car_insurance",
        "name": "Bilförsäkring",
        "description": "Försäkringsbrev, villkor och ersättningsregler för bil.",
        "fields": ["försäkringsbolag", "försäkringsnummer", "registreringsnummer", "självrisk", "giltig_till"],
        "retention": "Spara under försäkringstid och minst tre år efter avslut.",
        "keywords": ["bil", "försäkring", "krock", "självrisk", "vagnskada"],
    },
    {
        "id": "home_insurance",
        "name": "Hemförsäkring",
        "description": "Hemförsäkring, ansvar, reseskydd och lösöre.",
        "fields": ["försäkringsbolag", "försäkringsnummer", "adress", "lösöresbelopp", "giltig_till"],
        "retention": "Spara aktuell version och tidigare villkor vid pågående ärenden.",
        "keywords": ["hem", "försäkring", "resa", "lösöre", "ansvar"],
    },
    {
        "id": "personal_insurance",
        "name": "Personförsäkring",
        "description": "Liv-, olycksfalls-, barn- och sjukförsäkringar.",
        "fields": ["försäkrad", "försäkringsnummer", "förmånstagare", "belopp", "giltig_till"],
        "retention": "Spara så länge försäkringen gäller och under eventuella skadeärenden.",
        "keywords": ["person", "olycksfall", "sjuk", "livförsäkring"],
    },
    {
        "id": "claim_report",
        "name": "Skadeanmälan/olycksrapport",
        "description": "Skadeanmälningar, polisrapporter och korrespondens.",
        "fields": ["ärendenummer", "datum", "plats", "motpart", "status"],
        "retention": "Spara tills ärendet är helt avslutat och preskriptionstid passerat.",
        "keywords": ["skada", "olycka", "ärende", "rapport", "ersättning"],
    },
    {
        "id": "vehicle",
        "name": "Fordonsdokument",
        "description": "Registreringsbevis, service, besiktning och köpavtal.",
        "fields": ["registreringsnummer", "vin", "miltal", "datum", "verkstad"],
        "retention": "Spara under ägandet och vid försäljning som historik.",
        "keywords": ["fordon", "service", "besiktning", "registreringsbevis"],
    },
    {
        "id": "receipt",
        "name": "Kvitto",
        "description": "Kvitton för inköp, underlag och reklamation.",
        "fields": ["butik", "datum", "belopp", "moms", "betalmedel"],
        "retention": "Spara minst garantitiden eller enligt skattebehov.",
        "keywords": ["kvitto", "belopp", "moms", "inköp"],
    },
    {
        "id": "warranty_service",
        "name": "Garanti/service",
        "description": "Garantibevis, serviceavtal och reparationer.",
        "fields": ["produkt", "serienummer", "garanti_till", "leverantör", "ärendenummer"],
        "retention": "Spara under garanti- och reklamationstid.",
        "keywords": ["garanti", "service", "reparation", "serienummer"],
    },
    {
        "id": "tax_return",
        "name": "Skattedeklaration",
        "description": "Deklarationer och beslut från Skatteverket.",
        "fields": ["år", "beslutsdatum", "skatt", "rot_rut", "bilagor"],
        "retention": "Spara minst sju år om dokumentet styrker avdrag eller inkomster.",
        "keywords": ["deklaration", "skatt", "beslut", "avdrag"],
    },
    {
        "id": "tax_evidence",
        "name": "Skatteunderlag",
        "description": "Kontrolluppgifter, avdrag, resor och försäljningsunderlag.",
        "fields": ["år", "typ", "belopp", "motpart", "underlag"],
        "retention": "Spara minst sju år.",
        "keywords": ["underlag", "kontrolluppgift", "avdrag", "skatt"],
    },
    {
        "id": "bank_statement",
        "name": "Bankutdrag",
        "description": "Kontoutdrag, transaktionslistor och bankintyg.",
        "fields": ["bank", "konto", "period", "saldo", "valuta"],
        "retention": "Spara efter behov för skatt, tvister och större köp.",
        "keywords": ["bank", "konto", "utdrag", "transaktion"],
    },
    {
        "id": "loan_credit",
        "name": "Lån/kredit",
        "description": "Låneavtal, amorteringsplaner och kreditvillkor.",
        "fields": ["långivare", "avtalsnummer", "ränta", "löptid", "skuld"],
        "retention": "Spara tills lånet är avslutat och slutbesked finns.",
        "keywords": ["lån", "kredit", "ränta", "amortering"],
    },
    {
        "id": "housing_rent_fee",
        "name": "Hyra/bostad/avgift",
        "description": "Hyresavtal, avgiftsavier och bostadskorrespondens.",
        "fields": ["adress", "hyresvärd", "period", "belopp", "avtalsnummer"],
        "retention": "Spara under boendetiden och vid pågående tvist.",
        "keywords": ["hyra", "bostad", "avgift", "avi"],
    },
    {
        "id": "home_purchase",
        "name": "Bostadsköp/lagfart/avtal",
        "description": "Köpebrev, pantbrev, lagfart, mäklarhandlingar.",
        "fields": ["fastighet", "adress", "köpeskilling", "datum", "mäklare"],
        "retention": "Spara permanent eller så länge bostaden ägs.",
        "keywords": ["bostadsköp", "lagfart", "pantbrev", "köpebrev"],
    },
    {
        "id": "utilities",
        "name": "El, vatten och bredband",
        "description": "Avtal, fakturor och mätvärden för hushållstjänster.",
        "fields": ["leverantör", "anläggningsid", "period", "belopp", "förbrukning"],
        "retention": "Spara enligt reklamations- och jämförelsebehov.",
        "keywords": ["el", "vatten", "bredband", "faktura", "förbrukning"],
    },
    {
        "id": "medical_record",
        "name": "Medicinsk journal",
        "description": "Journalutdrag, provsvar och vårdkorrespondens.",
        "fields": ["vårdgivare", "datum", "diagnos", "läkare", "ärende"],
        "retention": "Spara långsiktigt och med extra försiktighet.",
        "keywords": ["journal", "provsvar", "diagnos", "vård"],
    },
    {
        "id": "prescription",
        "name": "Recept/läkemedel",
        "description": "Recept, läkemedelslistor och instruktioner.",
        "fields": ["läkemedel", "dos", "läkare", "giltig_till", "apotek"],
        "retention": "Spara medan behandlingen pågår och vid relevant historik.",
        "keywords": ["recept", "läkemedel", "dos", "apotek"],
    },
    {
        "id": "employment",
        "name": "Arbetsavtal",
        "description": "Anställningsavtal, villkor och intyg.",
        "fields": ["arbetsgivare", "roll", "startdatum", "lön", "uppsägningstid"],
        "retention": "Spara långsiktigt för pension, inkomst och tvister.",
        "keywords": ["anställning", "arbetsavtal", "lön", "villkor"],
    },
    {
        "id": "salary_pension",
        "name": "Lön/pension",
        "description": "Lönespecifikationer, pensionsbesked och intyg.",
        "fields": ["arbetsgivare", "period", "bruttolön", "skatt", "pensionsinstitut"],
        "retention": "Spara långsiktigt eller enligt skatte- och pensionsbehov.",
        "keywords": ["lön", "pension", "specifikation", "inkomst"],
    },
    {
        "id": "legal_contract",
        "name": "Juridiskt avtal/fullmakt",
        "description": "Avtal, fullmakter, testamenten och juridiska beslut.",
        "fields": ["part", "datum", "giltig_till", "jurist", "ärende"],
        "retention": "Spara permanent om dokumentet har lång rättsverkan.",
        "keywords": ["avtal", "fullmakt", "juridik", "testamente"],
    },
    {
        "id": "identity",
        "name": "Identitet/pass/körkort",
        "description": "Identitetshandlingar, kopior och giltighetsdatum.",
        "fields": ["typ", "nummer", "utfärdare", "giltig_till", "land"],
        "retention": "Spara säkert; radera gamla kopior när de inte behövs.",
        "keywords": ["pass", "körkort", "id", "identitet"],
    },
]

TEMPLATE_BY_ID = {item["id"]: item for item in DOCUMENT_TEMPLATES}
